import type { Trail } from '../types';

export const trails: Trail[] = [
  {
    slug: 'roman-legacy',
    name: 'The Roman Legacy',
    tagline: 'Lost technologies and crafts of an empire that achieved what we couldn\'t replicate for centuries.',
    description: 'Rome built roads that lasted two millennia, concrete that hardened underwater, and mechanisms that tracked the heavens. They seasoned their food with sauces and spices we can no longer taste. This trail traces the technologies and crafts of a civilization whose achievements we are still rediscovering.',
    icon: '🏛️',
    color: 'var(--color-accent)',
    entries: [
      { slug: 'silphium', transitionText: 'Rome achieved things we couldn\'t replicate for centuries. Their engineering, their chemistry, their cuisine — all reached heights that the medieval world could only marvel at. Start with the plant that bankrolled an entire region of the empire and whose extinction marked one of Rome\'s first irreplaceable losses.' },
      { slug: 'garum', transitionText: 'Silphium was rare and precious, but Rome\'s most universal condiment was something far more common — a fermented fish sauce so essential that an entire industry revolved around producing, shipping, and selling it across the empire.' },
      { slug: 'silphium-spice', transitionText: 'Garum flavored everything. But the seasoning the Romans prized above all others was silphium resin — worth its weight in silver, called for in dozens of recipes, and now permanently unavailable.' },
      { slug: 'tyrian-purple', transitionText: 'Roman luxury wasn\'t limited to the table. The most expensive color in the ancient world required twelve thousand sea snails to produce a single gram of dye — a chemical feat that took modern science until the 1990s to fully understand.' },
      { slug: 'samian-ware', transitionText: 'The Romans mass-produced luxury, too. Their fine tableware was made in industrial quantities using techniques that wouldn\'t be matched until the Industrial Revolution, then vanished so completely that the factories were forgotten.' },
      { slug: 'roman-concrete', transitionText: 'Roman engineering didn\'t just decorate tables — it built structures that have lasted two thousand years. Their concrete hardens underwater, and we only recently discovered why.' },
      { slug: 'roman-hydraulics', transitionText: 'The concrete held the structures. But Rome\'s real infrastructure miracle was water — moved across hundreds of miles through aqueducts, distributed through cities with pressurized pipe systems, and managed with engineering precision that modern utilities would recognize.' },
      { slug: 'roman-roads', transitionText: 'Water flowed through aqueducts. People and goods moved on roads — 80,000 kilometers of them, engineered to last and maintained by an empire that understood that connectivity was power.' },
      { slug: 'antikythera-mechanism', transitionText: 'The roads connected an empire. But perhaps the most startling artifact of Roman-era civilization wasn\'t infrastructure at all — it was a device that tracked the movements of the heavens with a precision that wouldn\'t be seen again for a thousand years.' },
      { slug: 'lycurgus-cup', transitionText: 'The Antikythera Mechanism used gears. But Roman craftspeople also worked at a scale they couldn\'t see — embedding gold and silver nanoparticles in glass to create a cup that changes color depending on how light hits it. Nanotechnology, fifteen hundred years before the concept existed. We\'re still discovering what Rome knew.' },
    ],
  },
  {
    slug: 'last-speakers',
    name: 'The Last Speakers',
    tagline: 'Languages dying one by one, each taking a unique way of seeing the world.',
    description: 'Every language encodes a unique way of categorizing reality — relationships, colors, time, kinship, the natural world. When a language dies, that perspective dies with it. This trail follows the last speakers, from Alaska to the Adriatic, and ends with humanity\'s attempt to send its languages into space.',
    icon: '📜',
    color: 'var(--color-cat-language)',
    entries: [
      { slug: 'eyak-language', transitionText: 'A language is not just vocabulary and grammar — it is a way of seeing the world. When Marie Smith Jones died in Alaska in 2008, the last native perspective encoded in Eyak died with her. She had spent decades trying to find someone to speak to. This trail follows the last speakers.' },
      { slug: 'ubykh', transitionText: 'Marie Smith Jones was the last Eyak speaker. Tevfik Esenç was the last speaker of Ubykh — a language with 84 consonants, the most complex sound system ever recorded. He died in Turkey in 1992, carrying an entire phonetic universe that no living throat can reproduce.' },
      { slug: 'dalmatian-language', transitionText: 'Ubykh vanished from the Caucasus. On the other side of the Mediterranean, a Romance language once spoken across the Dalmatian coast was reduced to a single elderly speaker on the island of Krk, who described his dying language to a linguist before a landmine killed him in 1898.' },
      { slug: 'yahi', transitionText: 'Tuone Udaina lost his language. Ishi lost everything — he walked out of the California wilderness in 1911 as the last surviving member of the Yahi people, the last speaker of a language that had been spoken for thousands of years, and lived his remaining years in a museum.' },
      { slug: 'kusunda', transitionText: 'Ishi\'s language vanished completely. But sometimes a language survives by a thread. Kusunda, a language isolate spoken in Nepal with no known relatives, was thought extinct until a single speaker was found in 2004 — a woman who hadn\'t spoken it in decades.' },
      { slug: 'ayapaneco', transitionText: 'Kusunda had one speaker. Ayapaneco, in Tabasco, Mexico, had two — but they refused to speak to each other. A language that required only a conversation to survive, silenced by a personal grudge.' },
      { slug: 'silbo-gomero', transitionText: 'Not all endangered languages are spoken. On the island of La Gomera, an entire language is whistled — carrying across the deep ravines that make the island nearly impassable. Silbo Gomero was fading until the government made it mandatory in schools, buying it time.' },
      { slug: 'voyager-golden-record', transitionText: 'Silbo Gomero was saved, for now. But some of the languages we\'ve sent into space on the Voyager Golden Record — greetings in 55 languages launched in 1977 — are already dying or dead on Earth. We broadcast languages to the stars that we couldn\'t keep alive at home.' },
    ],
  },
  {
    slug: 'climates-toll',
    name: "Climate's Toll",
    tagline: 'Water rising, water vanishing. The pace is accelerating.',
    description: 'Climate has always reshaped the planet. But the changes accelerating now — rising seas, drying lakes, dying reefs, retreating glaciers — are not the slow rhythms of geological time. They are happening within a human lifetime. This trail traces the toll, from ancient sea level rise to modern devastation.',
    icon: '🌊',
    color: 'var(--color-cat-place)',
    entries: [
      { slug: 'doggerland', transitionText: 'Eight thousand years ago, you could walk from England to Denmark. A land bridge called Doggerland connected Britain to continental Europe — home to Mesolithic hunters, marshes, rivers, and forests. Then the seas rose, and an entire country vanished beneath the North Sea. Climate has always reshaped the world.' },
      { slug: 'bramble-cay-melomys', transitionText: 'Doggerland took millennia to flood. Bramble Cay — a tiny island in the Torres Strait — lost its only mammal in just a few decades. The Bramble Cay melomys, a small rodent, was declared extinct in 2019 — the first confirmed mammalian extinction directly caused by modern climate change.' },
      { slug: 'golden-toad', transitionText: 'The melomys lived on a sinking island. The golden toad lived in a cloud forest — and vanished when the clouds changed. Last seen in 1989 in Costa Rica, its extinction is linked to shifting weather patterns and the spread of chytrid fungus through warming, drying habitats.' },
      { slug: 'aral-sea', transitionText: 'The golden toad needed a stable cloud forest. The Aral Sea needed its rivers. When the Soviet Union diverted the Amu Darya and Syr Darya to irrigate cotton fields, the fourth-largest lake in the world began to disappear — a man-made climate catastrophe visible from space.' },
      { slug: 'sundarbans-shrinking', transitionText: 'The Aral Sea was drained by human hands. The Sundarbans — the world\'s largest mangrove forest — is being eroded by rising seas and intensifying cyclones. The forest that protects millions of people from storm surges is itself disappearing.' },
      { slug: 'cedars-of-lebanon', transitionText: 'The Sundarbans are shrinking. The cedars of Lebanon have been shrinking for millennia — harvested by empires from Mesopotamia to Rome, and now further stressed by warming temperatures pushing their habitat upslope. A tree that once covered a nation reduced to scattered groves.' },
      { slug: 'lake-pedder', transitionText: 'The cedars lost their forests over millennia. Lake Pedder in Tasmania was lost in a single decision — flooded in 1972 by a hydroelectric dam, despite intense environmental protest. An irreplaceable glacial lake with endemic species, drowned in the name of electricity. The pace is accelerating.' },
    ],
  },
  {
    slug: 'lost-flavors',
    name: "Flavors We'll Never Taste",
    tagline: 'An entire dinner party of foods we can read about but never eat.',
    description: 'Imagine hosting a dinner where every course features a food that no longer exists. Roman fish sauce, Aztec chocolate, a pear that made Victorian grown men weep, and a banana your grandparents ate that was replaced by an inferior cultivar. This trail sets the table.',
    icon: '🍐',
    color: 'var(--color-cat-food)',
    entries: [
      { slug: 'silphium-spice', transitionText: 'Welcome to a dinner party of ghosts. Every dish on this table features an ingredient that no longer exists — a flavor that was once someone\'s everyday pleasure and is now permanently beyond reach. We begin with the seasoning that defined Roman haute cuisine.' },
      { slug: 'garum', transitionText: 'Silphium flavored Roman food for centuries. But it wasn\'t the only seasoning Rome lost. Their most universal condiment was a fermented fish sauce so essential that an entire economy revolved around it.' },
      { slug: 'aztec-chocolate', transitionText: 'Rome had garum. The Aztec empire had cacao — but not the sweet chocolate we know. Their xocolātl was bitter, spicy, and mixed with chili and cornmeal. The drink that conquered Europe was already a pale imitation of what Montezuma drank.' },
      { slug: 'ansault-pear', transitionText: 'From the Aztec court to a 19th-century greenhouse. The Ansault pear was so exquisite that Victorian pomologists ran out of superlatives. It required grafting techniques that couldn\'t survive the decline of estate gardens. The last tree died in the early 1900s.' },
      { slug: 'gros-michel-banana', transitionText: 'The Ansault pear was a luxury. The Gros Michel banana was an everyday fruit — the banana your grandparents ate, creamier and more intensely flavored than the Cavendish we eat today. A fungal pandemic wiped it from commercial production in the 1950s.' },
      { slug: 'taliaferro-apple', transitionText: 'The banana was replaced. The Taliaferro apple simply vanished — Thomas Jefferson\'s favorite cider apple, grown at Monticello, lost when the orchards declined after his death. We have his notes. We don\'t have the tree.' },
      { slug: 'claxton-peach', transitionText: 'Jefferson lost his apple. Georgia lost its peach. The Claxton peach, the definitive Southern peach, was bred for flavor in an era when fruit was selected for taste, not shelf life. Modern commercial peaches are engineered to survive shipping. The Claxton couldn\'t.' },
      { slug: 'passenger-pigeon-pie', transitionText: 'From the orchard to the sky. Passenger pigeon pie was once so common it was poor people\'s food — billions of birds reduced to zero in fifty years, and with them, a flavor that was as ordinary as chicken.' },
      { slug: 'original-ny-cheesecake', transitionText: 'The pigeon pie fed the masses. The original New York cheesecake was an immigrant creation — made with specific local dairy and techniques that the standardization of commercial baking gradually erased.' },
      { slug: 'okinawan-awamori', transitionText: 'Dessert, then a drink. Okinawan awamori — the oldest distilled spirit in Japan — maintained living cultures of black koji mold passed down for centuries. The Battle of Okinawa in 1945 destroyed the oldest cultures. What survives is a reconstruction, not the original. The dinner is over. Every dish is gone.' },
    ],
  },
  {
    slug: 'destroyed-by-conquest',
    name: 'Destroyed by Conquest',
    tagline: 'What happens when one civilization destroys another\'s knowledge.',
    description: 'Libraries burned, codices incinerated, languages silenced, cities drained. When an empire conquers another, it doesn\'t just take territory — it destroys the conquered civilization\'s ability to remember itself. This trail follows the pattern from Alexandria to California.',
    icon: '🔥',
    color: 'var(--color-cat-culture)',
    entries: [
      { slug: 'library-of-alexandria', transitionText: 'The greatest library in the ancient world held hundreds of thousands of scrolls — the accumulated knowledge of the Mediterranean civilizations. Its destruction, gradual and multi-causal, wasn\'t a single fire but a slow dismantling by successive conquerors who valued power over knowledge.' },
      { slug: 'nalanda', transitionText: 'Alexandria was the West\'s great library. Nalanda was the East\'s — a Buddhist university in India with nine million manuscripts, operational for 800 years, until Turkic invaders burned it in 1193. The monks who fled carried what they could. The rest fueled fires for months.' },
      { slug: 'mixtec-codices', transitionText: 'Nalanda burned in South Asia. In Mesoamerica, Spanish friars performed their own intellectual destruction — burning Mixtec and Aztec codices by the thousands. The few that survived, hidden or overlooked, are among the most precious documents in the Americas.' },
      { slug: 'quipu', transitionText: 'The Mixtec recorded knowledge in painted books. The Inca recorded it in knotted strings — quipu. The Spanish destroyed them as instruments of idolatry, not realizing they were destroying an empire\'s administrative records, its history, its literature.' },
      { slug: 'benin-bronzes', transitionText: 'The Spanish burned quipu in South America. In 1897, the British burned the Kingdom of Benin and looted thousands of bronze plaques — sophisticated artworks that documented centuries of West African history. Many remain in European museums.' },
      { slug: 'lake-texcoco', transitionText: 'The British looted Benin\'s art. The Spanish went further in Mexico — draining Lake Texcoco, the body of water on which the Aztec capital Tenochtitlán stood. They didn\'t just conquer a city. They erased the landscape it was built on.' },
      { slug: 'great-hedge-india', transitionText: 'The Spanish drained a lake to erase a capital. The British built a hedge across India — a 3,700-kilometer barrier to enforce salt taxes on a colonized population. An entire landscape was reshaped to extract revenue from the conquered.' },
      { slug: 'eyak-language', transitionText: 'Conquest doesn\'t always involve armies. The colonization of Alaska silenced languages through assimilation policies, mission schools, and the slow pressure of a dominant culture. Eyak didn\'t die in battle. It died in silence.' },
      { slug: 'yahi', transitionText: 'Eyak faded. The Yahi people of California didn\'t fade — they were systematically hunted. Ishi, the last survivor, walked out of the wilderness in 1911 carrying a language, a culture, and a history that existed only in his memory. When he died, it all went with him.' },
    ],
  },
  {
    slug: 'lost-secrets',
    name: 'Secrets That Died With Their Makers',
    tagline: 'Formulas and techniques that one person or one era knew and nobody since has replicated.',
    description: 'Some knowledge dies because it was never written down. Some dies because the conditions that produced it no longer exist. And some dies because one person held a secret and took it to the grave. This trail follows the lost recipes, formulas, and techniques.',
    icon: '🔮',
    color: 'var(--color-cat-technology)',
    entries: [
      { slug: 'greek-fire', transitionText: 'Some secrets are kept so well that they outlast the civilization that created them. Byzantine Greek fire — a weapon that burned on water, terrified enemies for centuries, and was guarded so tightly that even the Byzantines eventually forgot how to make it.' },
      { slug: 'damascus-steel', transitionText: 'Greek fire was a military secret. Damascus steel was an industrial one — blades with distinctive watered patterns and legendary sharpness, forged from crucible steel whose exact production method was lost by the 1800s. Modern metallurgists have come close but never exactly matched it.' },
      { slug: 'stradivarius-secret', transitionText: 'Damascus steel was lost when its supply chain collapsed. Stradivarius violins were lost when their maker died — Antonio Stradivari took whatever combination of wood, varnish, and technique made his instruments exceptional to his grave in 1737.' },
      { slug: 'starlite', transitionText: 'Stradivari\'s secret was the work of a lifetime. Starlite was the work of one amateur — Maurice Ward, a British hairdresser who invented a plastic that could withstand temperatures of 10,000°C. He demonstrated it on national television. He never revealed the formula. He died in 2011.' },
      { slug: 'mummy-brown', transitionText: 'Ward took Starlite to his grave. The Pre-Raphaelite painters used a pigment made from ground-up Egyptian mummies — mummy brown. When supplies of real mummies ran out, the color vanished. One painter reportedly buried his tube of mummy brown when he learned what it contained.' },
      { slug: 'fordite', transitionText: 'Mummy brown was made from the dead. Fordite was made by accident — layers of automotive paint that built up in car factory spray booths, hardening over decades into a geological-looking material. When factories automated their paint lines, fordite stopped forming.' },
      { slug: 'kodachrome', transitionText: 'Fordite was an accidental byproduct. Kodachrome was an intentional masterpiece — a color film with a look so distinctive that it defined how we see the 20th century. Kodak discontinued it in 2009 because digital photography made it obsolete.' },
      { slug: 'bakelite', transitionText: 'Kodachrome captured the world in color. Bakelite was the first fully synthetic plastic — the material that launched the plastics age. Its specific formulation was eventually superseded by cheaper, more versatile polymers, and the original Bakelite production process was abandoned. We ended with the material that started modernity.' },
    ],
  },
  {
    slug: 'loneliest-creatures',
    name: 'The Loneliest Creatures',
    tagline: 'The last of their kind. Singing for mates that don\'t exist. Standing alone on a ridge.',
    description: 'There is a moment in every extinction when the population drops to one. One bird singing a duet alone. One plant waiting for a mate that will never arrive. One turtle in a zoo that represents the future of a species. This trail is about those final individuals.',
    icon: '🕊️',
    color: 'var(--color-cat-fauna)',
    entries: [
      { slug: 'kauai-oo', transitionText: 'This trail is about endings. Not the abstract kind — the specific, individual kind. A single creature, the last of its lineage, alone in a world that has moved on. We begin with a bird singing a duet for a partner that no longer exists.' },
      { slug: 'pyrenean-ibex', transitionText: 'The Kaua\'i \'O\'o sang into silence. The Pyrenean ibex died on January 6, 2000 — the last one killed by a falling tree. Scientists cloned it in 2003. The clone lived for seven minutes before dying of a lung defect. The species went extinct twice.' },
      { slug: 'thylacine', transitionText: 'The ibex was cloned and died again. The thylacine — the Tasmanian tiger — died in a zoo in 1936. The last known individual, sometimes called Benjamin, paced in a concrete enclosure at the Hobart Zoo. Film footage shows it yawning, pacing, lying down. The last of its kind, on camera, bored and alone.' },
      { slug: 'baiji', transitionText: 'The thylacine died in captivity. The baiji — the Yangtze river dolphin — vanished from the wild. A 2006 survey of its entire range found nothing. A species that had swum the Yangtze for 20 million years, gone in the span of China\'s industrialization.' },
      { slug: 'cafe-marron', transitionText: 'From animals to plants — but loneliness is the same. The café marron was discovered in 1980 as a single plant growing in a schoolyard on Rodrigues Island. One individual of an unknown species. Every café marron alive today is a cutting from that one plant.' },
      { slug: 'bois-dentelle', transitionText: 'One café marron in a schoolyard. Two bois dentelle trees on a ridge in Mauritius — a species reduced to two individuals, their lace-like flowers found nowhere else on Earth. Their survival depends on whether those two trees can produce viable seed.' },
      { slug: 'yangtze-softshell-turtle', transitionText: 'Two bois dentelle trees. Three or fewer Yangtze giant softshell turtles — the most endangered turtle in the world. For years, a lone male in a Chinese zoo was paired with a female for breeding. She died during artificial insemination in 2019. The species\' future is measured in single digits.' },
      { slug: 'alala-song', transitionText: 'The turtle waits in a concrete pool. The \'alal\u0101, the Hawaiian crow, once filled the forests of Hawai\'i Island with a rich, complex vocabulary of calls. By 2002, the last two wild birds vanished. Captive-bred \'alal\u0101 have been released, but the songs they sing are simplified versions — learned in aviaries, not from wild parents. The full wild song, passed down through generations, is gone. Some loneliness can be undone. Some cannot.' },
    ],
  },
];

export function getTrail(slug: string): Trail | undefined {
  return trails.find(t => t.slug === slug);
}

export function getTrailsForEntry(entrySlug: string): Trail[] {
  return trails.filter(t => t.entries.some(e => e.slug === entrySlug));
}
