import type { Entry } from '../../types';

export const cedarsOfLebanon: Entry = {
  slug: 'cedars-of-lebanon',
  name: 'The Cedars of Lebanon',
  tagline: 'The most famous forest in the ancient world. Gilgamesh wrote about it. Solomon built a temple from it. The forest is gone.',
  category: 'flora',
  subcategory: 'Ancient Forests',
  lastKnownYear: '~1900',
  lastKnownLocation: 'Mount Lebanon, Lebanon',
  coordinates: [34.25, 36.06],
  region: 'Middle East',
  status: 'functionally_extinct',
  cause: 'Millennia of harvesting by Phoenicians, Egyptians, Assyrians, Romans, and Ottomans, followed by modern development',
  imageUrl: undefined,
  imageCaption: undefined,
  imageCredit: undefined,
  body: `## The Forest That Built Civilization

The species Cedrus libani is not extinct. Scattered trees and a few small groves still stand on the slopes of Mount Lebanon. But the cedar forest — the vast, ancient ecosystem that once covered the mountains of the eastern Mediterranean and shaped the course of Western civilization — is gone. It was gone by the early twentieth century, after the Ottomans felled the last large stands for railroad ties and the British took what remained during the World Wars. What survives are fragments: roughly 2,000 hectares of scattered groves, remnants of a forest that ancient texts describe as taking days to cross.

The Epic of Gilgamesh, written around 2100 BCE, describes a cedar forest of terrifying vastness guarded by the monster Humbaba. The hero Gilgamesh travels to this forest and fells its greatest trees, an act presented as both triumph and transgression. It may be the oldest surviving narrative about deforestation. The cedars were already famous enough, and already threatened enough, to structure one of humanity's first stories.

## Everyone Wanted Them

The cedar of Lebanon was the most prized building material in the ancient world. The wood is aromatic, insect-resistant, strong, straight-grained, and slow to rot. It was the steel and concrete of the Bronze Age. The Phoenicians built their trading fleet from Lebanese cedar -- the ships that established maritime commerce across the Mediterranean. Egyptian pharaohs imported cedar for temple construction, ship-building, and coffins. The earliest known international trade agreements include provisions for cedar supply.

Solomon's Temple in Jerusalem, described in the Book of Kings, was built primarily from Lebanese cedar, supplied by King Hiram of Tyre. The Assyrians, Babylonians, Persians, Greeks, and Romans all harvested the forests. The Roman Emperor Hadrian, recognizing the depletion, placed boundary stones around the remaining groves in the second century CE, inscribing them with prohibitions against felling certain species. These boundary stones still exist. The forests they were meant to protect do not.

## Five Thousand Years of Cutting

The Ottoman Empire continued the harvesting for railroad construction in the nineteenth century. The British used Lebanese timber during both World Wars. By the twentieth century, the once-vast forests had been reduced to scattered groves, the largest being the Cedars of God grove near Bsharri, which contains approximately 375 trees, some estimated to be over 1,000 years old.

Lebanon placed the cedar on its national flag — an emblem of what no longer exists. The remaining groves are protected, and seedlings have been planted, but a cedar takes centuries to reach maturity, and the ecological web that sustained the original forest — the soil mycorrhizae, the understory species, the wildlife communities, the microclimate generated by continuous canopy cover over thousands of square kilometers — is permanently destroyed. You can grow cedars. You cannot regrow the Cedar Forest. The ecosystem is gone.

## What Was Lost

The loss is not merely ecological. The cedar forests of Lebanon were the economic engine of the ancient eastern Mediterranean. The Phoenician civilization, the first great maritime trading culture, was built on cedar hulls. Solomon's Temple, one of the most significant structures in religious history, was framed in cedar beams. The forests shaped trade routes, powered empires, and generated wealth for millennia. They were harvested by every major civilization that controlled the Levant, each one taking what it needed and leaving less for the next. The cedar on Lebanon's flag is an emblem of what the country once had and what the world took. The forest that built civilization was consumed by it.`,
  quickFacts: {
    'Species': 'Cedrus libani',
    'Original Range': 'Mountains of Lebanon, Syria, and southern Turkey',
    'Remaining Groves': '~12, totaling roughly 2,000 hectares',
    'Oldest Trees': 'Estimated 1,000+ years (Cedars of God grove, Bsharri)',
    'Earliest Written Reference': 'Epic of Gilgamesh (~2100 BCE)',
    'Biblical Reference': 'Solomon\'s Temple (1 Kings 5-6)',
    'National Symbol': 'Featured on the flag of Lebanon',
    'Protection': 'UNESCO World Heritage Site (Cedars of God)',
  },
  connections: [
    { slug: 'silphium', relationship: 'Both were prized natural resources of the ancient world harvested continuously by successive civilizations until near-total depletion' },
    { slug: 'aral-sea', relationship: 'Both were once-vast natural features reduced to remnants by millennia of human exploitation, leaving only fragments of their original scale' },
  ],
  sources: [
    { title: 'The Cedars of Lebanon: Significance, Awareness and Management of the Cedrus libani in Lebanon', author: 'Nemer Frayha', year: 2006 },
    { title: 'A Forest Journey: The Story of Wood and Civilization', author: 'John Perlin', year: 2005 },
    { title: 'The Epic of Gilgamesh', author: 'Andrew George (translator)', year: 1999 },
    { title: 'Ecology, Biogeography and Management of Cedrus libani', author: 'Nabil Nemer and others', year: 2019 },
  ],
};
